openshift/router

OWNERS

/cc @openshift/sig-network-edge @smarterclayton

owners: update approvers and reviewers

---

pkg/router/template/router.go

Respect route targetPort in dynamic config

---

OWNERS

Add @danehans to the reviewers.

Update OWNERS to add danehans

---

LICENSE

Following https://github.com/openshift/origin.
Closes #54.

Add LICENSE file: Apache License, Version 2.0

---

Makefile
pkg/cmd/infra/router/router.go
pkg/cmd/infra/router/template.go
pkg/version/version.go

Fix git version reporting in the build scripting and `version` subcommand.

Bug 1774353: fix version reporting

---

pkg/router/controller/status.go

If a status update fails with a forbidden error, retry the update.
Keep retrying failed updates as long as the route has the wrong status.
* `pkg/router/controller/status.go` (`performIngressConditionUpdate`): Retry on forbidden errors.  Never give up retrying after an error.

Bug 1780398: status: performIngressConditionUpdate: Retry on 403

---

cmd/openshift-router/main.go
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel

Testing to see whether we have uncovered error paths resulting in
readiness failures.

Set log level 2 by default

---

images/router/haproxy/conf/haproxy-config.template

cherry-picked changes from #90

Bug 1816544: [4.4] Backport "remove proto-version header field"

---

images/router/haproxy/conf/haproxy-config.template

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1854814
See also: https://github.com/openshift/router/pull/123

Bug 1854814: Removes ALPN from haproxy backends

---

OWNERS

Add myself (candita) to OWNERS

addowner-candita

---

pkg/cmd/infra/router/template.go

pkg/cmd/infra/router/template.go: Pass the stopCh parameter from the Run function to the RouterControllerFactory.Create calls (as opposed to using a hard-coded wait.NeverStop). This is to ensure that the RouterController(s) are stopped during a router pod's termination process. This prevents router pods from a previous deployment that are in the process of terminating from fighting with newly created router pods over route admission status.
This resolves BZ-1903821, in which toggling the router deployment's ROUTER_DISABLE_NAMESPACE_CHECK can result in inactive routes holding an "Admitted: True" condition.
--- 
See https://github.com/openshift/router/pull/94 for context when the `Run` function in `pkg/cmd/infra/router/template.go` added the `stopCh` parameter.
Also see …

Bug 1903821: Pass stop channel to RouterControllers

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

Switch to haproxy22 package. This is a move from haproxy-2.0 series to haproxy-2.2.

Switch to haproxy22

---

images/router/haproxy/conf/error-page-404.http
images/router/haproxy/conf/haproxy-config.template
images/router/haproxy/reload-haproxy

Add errorfile stanzas and dummy default html files to the router
https://issues.redhat.com/browse/NE-379

Add errorfile stanzas and dummy default html files to the router

---

pkg/cmd/infra/router/template.go

This commit adds the capability to specify router
stats (metrics) authentication credentials via separate
username and password files.
This commit does not remove the prior behavior, in which stats
credentials are fed into the router via the STATS_USERNAME
and STATS_PASSWORD environment variables. These environment
variables are ignored when both STATS_PASSWORD_FILE and
STATS_USERNAME_FILE are provided.
pkg/cmd/infra/router/template.go:
Add new startup options, `stats-user-file` and `stats-password-file`.
Add a new helper function, `getStatsAuth`, that
returns the contents of STATS_USERNAME_FILE and STATS_PASSWORD_FILE,
or the values set in STATS_USERNAME and STATS_PASSWORD, depending on which
are provided. Preference is given to stats auth credentials provided via
files.
This commit is …

Bug 1955822: cmd: Add option to source stats auth from file

---

hack/Dockerfile.debug
images/router/base/Dockerfile.rhel
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

build: switch to haproxy24 RPM

---

images/router/haproxy/conf/error-page-404.http
images/router/haproxy/conf/error-page-503.http
images/router/nginx/conf/error-page-503.html

Manual cherry-pick of https://github.com/openshift/router/pull/300 ([robot cherry pick](https://github.com/openshift/router/pull/300#issuecomment-860787705) failed).

 [release-4.8] Bug 1971730: error pages - don't use bootstrap/normalize

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

Manual backport of https://github.com/openshift/router/pull/307

[release-4.8] Bug 1984565: config template: accept IPv6 IPs for whitelisting

---

deploy/route_crd.yaml
deploy/router_rbac.yaml

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

Bug 1928932: Update deploy manifests to use stable apis

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Bump prometheus/client_golang to v1.11.1

BUG 2067778: Bump prometheus/client_golang to v1.11.1

---

pkg/cmd/infra/router/router.go

If a route has an empty `spec.host` and a nonempty `spec.subdomain` and the router has a domain configured, use the route's subdomain and router's domain as the route's host.
* `pkg/cmd/infra/router/router.go` (`RouterSelection`): Add `RouterDomain` field.
(`Bind`): Add a `--router-domain` flag and `ROUTER_DOMAIN` environment variable to specify the router's domain.
(`RouteUpdate`): Set the route's `spec.host` using the route's subdomain and router's domain if the host is empty and the subdomain and domain are nonempty.

NE-882: Support subdomain field when host is unset

---

pkg/router/template/router.go
pkg/router/template/router_test.go

Previously, you could have a service with two different ports and openshift-router would count both, regardless of what `route.spec.port.targetPort` was configured to. This change uses the route's targetPort when counting endpoints. This 
impacts weights for alternateBackends as well a bug in which a service with two ports could enable backend health checks, despite only having one server.
- `pkg/router/template/router.go`: Added the port parameter to getActiveEndpoints, calculateServiceWeights, and numberOfEndpoints.
- `pkg/router/template/router_test.go`: Updated unit testing for calculateServiceWeights to provide port.

OCPBUGS-5073: Count endpoints per port for weights and enabling active health checks

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

https://issues.redhat.com/browse/NE-1304

NE-1304: container builds: switch to haproxy26 package

---

OWNERS

Adds grzpiotrowski to the OWNERS file.

NO-JIRA: Add grzpiotrowski to the OWNERS file

---

OWNERS

Update OWNERS file with Thealisyed to reflect current team

NO-JIRA: Update OWNERS file to reflect current team

---

OWNERS

NO-JIRA: Add rikatz to OWNERS
