images/router/haproxy/conf/haproxy-config.template

Starting in HAProxy 1.8 the 'option tcplog' cannot be used in the
backends any more. I removed 'option tcplog' from the backend, the
logging option is appropriately selected in the frontend already
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#option%20tcplog
Fixes
bug 1579729
https://bugzilla.redhat.com/show_bug.cgi?id=1579729

Remove 'option tcplog' from passthrough backend in template router

---

pkg/router/controller/hostindex/hostindex.go
pkg/router/controller/hostindex/hostindex_test.go

Fix broken update handling of path-based routes
When an existing route's path is updated to a new value not previously observed,
the new route state is correctly activated, but the previous route is not
replaced in the `hostRules` internal active list. Instead, the updated route
state (with a different path but duplicate UID) is appended to the active list.
A `hostRules` active list with more than one route instance sharing a UID and
host is an invalid internal state. The net effect is some unintended confusing
behavior which manifests when updating the route's path, including:
* Updating from path A->B->A preventing future transitions to B
* Updating from path A->B->A->B leaves an orphaned claim on the host in the
namespace, preventing the recreation of the route with either of the …

Fix broken update handling of path-based routes

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel

The HAProxy reload script uses pidof which is not always installed.

image: Declare explicit dependency on sysvinit-tools

---

pkg/router/controller/host_admitter.go
pkg/router/controller/host_admitter_test.go

Pull from origin PR: https://github.com/openshift/origin/pull/22087
As part of the resync processing, wildcard routes get a "HostAlreadyClaimed"
error and then later as part of the same event processing flow, the route
gets re-added. This results in a temporary outage (route returns 503s).
fixes #1660647 (https://bugzilla.redhat.com/show_bug.cgi?id=1660647)
@openshift/sig-network-edge  PTAL Thx

Fix issue where wildcard routes get 503s intermittently.

---

pkg/router/template/configmanager/haproxy/blueprint_plugin.go
pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
pkg/router/template/configmanager/haproxy/manager.go
pkg/router/template/types.go

Follow up to refactor the blueprint validation code.
Migrated from: https://github.com/openshift/origin/pull/20722

Refactor haproxy router config manager blueprint validation code.

---

images/router/haproxy/conf/haproxy-config.template

Always seeing an extra `}` after the `timeout check 5000ms` and affecting all pass through route, so remove it from the template.
here is example of haproxy.config
```
backend be_tcp:openshift-authentication:openshift-authentication
balance source
hash-type consistent
timeout check 5000ms}
```

remove an extra brace from the template

---

pkg/router/template/router.go

When writing out routes' certificates, the template router logs a message for each edge or reencrypt route that does not specify certificates.  If the router has a default certificate, this message is supposed to be logged to INFO.  If the router does not have a default certificate, this message is supposed to be logged to WARNING.
Before this commit, the relevant check for the default certificate was using the wrong value (namely the `defaultCertificate` value, which is set only if the default certificate is passed to the router on the command-line or in an environment variable).  Consequently, the router was logging the message to WARNING in some cases when the router had a default certificate.
After this commit, the check uses the correct value (namely the `defaultCertificatePath` …

Bug 1679941: shouldWriteCerts: Fix check for default certificate

---

images/router/haproxy/reload-haproxy

Delete the `haproxy_conf_dir` variable, which is no longer used as of https://github.com/openshift/origin/pull/19219.
* `images/router/haproxy/reload-haproxy`: Delete unused variable.

reload-haproxy: Delete unused haproxy_conf_dir var

---

Gopkg.lock
pkg/router/template/router.go
vendor/github.com/fsnotify/fsnotify/.editorconfig
vendor/github.com/fsnotify/fsnotify/.gitignore
vendor/github.com/fsnotify/fsnotify/.travis.yml
vendor/github.com/fsnotify/fsnotify/AUTHORS
vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
vendor/github.com/fsnotify/fsnotify/LICENSE
vendor/github.com/fsnotify/fsnotify/README.md
vendor/github.com/fsnotify/fsnotify/fen.go
vendor/github.com/fsnotify/fsnotify/fsnotify.go
vendor/github.com/fsnotify/fsnotify/inotify.go
vendor/github.com/fsnotify/fsnotify/inotify_poller.go
vendor/github.com/fsnotify/fsnotify/kqueue.go
vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
vendor/github.com/fsnotify/fsnotify/windows.go

* `pkg/router/template/router.go` (`watchSecretDir`): New method.  Establish a watch on the specified path, and rewrite the default certificate when the watch detects changes.
(`writeDefaultCert`): Call `watchSecretDir` to watch the directory with the default certificate secret.
---
@openshift/sig-network-edge

Bug 1701410: Rewrite default certificate when secret is updated

---

pkg/router/metrics/haproxy/haproxy.go

When `ServerThreshold` is exceeded, it doesn't ignore the rest of the servers, it ignores the rest of the records including backend, frontend and server records. 
```go
// If we exceed the server threshold, ignore the rest of the servers because we will be
// displaying only backends and frontends.
if row[32] == serverType {
servers++
}
// --> Issue is here:
if servers > e.opts.ServerThreshold {
continue 
}
rows++
e.parseRow(row, targetValues)
```
This PR fixes this issue. 
BTW, the older versions also have this issue, do you think I can backport this fix to those versions as well? 
3.10.0: https://github.com/openshift/origin/blob/v3.10.0/pkg/router/metrics/haproxy/haproxy.go#L428-L438
3.11.0: https://github.com/openshift/origin/blob/v3.11.0/pkg/router/metrics/haproxy/haproxy.go#L428-L438

Fix ignoring non-server records when server threshold is exceeded

---

images/router/haproxy/conf/haproxy-config.template

`proto-version` may be empty when http/2 is not enabled (the default), and empty values
must be surrounded by quotes as per https://tools.ietf.org/html/rfc7239
Applications may fail to parse the header if not complying with the RFC

Comply with RFC7239 for Forwarded header

---

images/router/haproxy/conf/haproxy-config.template

This exposes the min-tls-ver and max-tls-ver as router environment
variables.
*  SSL_MIN_VERSION - Optional - Default is TLSv1.2
*  SSL_MAX_VERSION - Optional, no default (so the max is whatever haproxy supports)
Fixes bug 1746467
https://bugzilla.redhat.com/show_bug.cgi?id=1746467

Bug 1746467: Expose control of the tls settings via router ENV

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

With extended validation enabled, if the router detects an ECDSA private key when processing TLS data,
the sanitized key output is rendered with PEM block headers like:
-----BEGIN ECDSA PARAMETERS-----
-----END ECDSA PARAMETERS-----
However, OpenSSL recognizes the following headers for ECDSA keys[1]:
-----BEGIN EC PARAMETERS-----
-----END EC PARAMETERS-----
Consequently, when the router provides haproxy with such PEM files through
`crt-list` option, haproxy (which uses OpenSSL) fails to load the key and reload
fails.
The impact is that a Route resource containing an ECDSA key in `.spec.tls.key`
will cause haproxy reloads to crash loop, preventing any further router
processing until the problematic Route is deleted.
This patch ensures that sanitized RCDSA key output follows the OpenSSL …

Bug 1723400: fix haproxy reload crash when processing ECDSA keys

---

pkg/cmd/infra/router/template.go
pkg/router/template/plugin.go
pkg/router/template/router.go

Before this commit, the router used the endpoints of a "peer" service to discover peer router instances and made a list of these peer endpoints available to the configuration template.  However, the default template does not use peer endpoints, and the feature is not documented.
The feature is left over from an early implementation of sticky sessions (https://github.com/openshift/origin/pull/2105/commits/4c52fd188166cb5788f0bd249385b49cd5d9a7ff), which used peer endpoints to configure peers in `haproxy`.config.  However, the implementation of sticky sessions that was merged did not use peers, and no other users exist.
* `pkg/cmd/infra/router/template.go` (`Complete`, `Run`): Delete the router peer service from the template-router options.
* `pkg/router/template/plugin.go` …

Delete tracking of peer endpoints

---

pkg/router/template/router.go

Convert the reload script's output from a byte slice to a string before logging it so that it is displayed properly.  Before https://github.com/openshift/router/pull/47/commits/dc68ebfcbd9fdc600391ebe050228534dd2b07c3, log messages looked like the following:
Router reloaded:
- Proxy protocol on, checking http://localhost:80 ...
- Health check ok : 0 retry attempt(s).
Since that change, the reload script's output is base64-encoded in logs:
router reloaded	{"output": "IC0gUHJveHkgcHJvdG9jb2wgb24sIGNoZWNraW5nIGh0dHA6Ly9sb2NhbGhvc3Q6ODAgLi4uCiAtIEhlYWx0aCBjaGVjayBvayA6IDAgcmV0cnkgYXR0ZW1wdChzKS4K"}
This PR restores the previous, non-encoded log messages.
* `pkg/router/template/router.go` (`reloadRouter`): Convert `out` to string.
----

Stop base64-encoding "router reloaded" log output

---

pkg/router/template/configmanager/haproxy/backend.go
pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
pkg/router/template/configmanager/haproxy/client.go
pkg/router/template/configmanager/haproxy/client_test.go
pkg/router/template/configmanager/haproxy/manager.go
pkg/router/template/configmanager/haproxy/map.go
pkg/router/template/configmanager/haproxy/map_test.go
pkg/router/template/fake.go
pkg/router/template/plugin.go
pkg/router/template/plugin_test.go
pkg/router/template/router.go
pkg/router/template/router_test.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go
pkg/router/template/types.go

Define and use the `ServiceUnitKey` and `ServiceAliasConfigKey` types for key values of maps of `ServiceUnit` values and of `ServiceAliasConfig` values, respectively, in order to make code dealing with such maps clearer and reduce risk of mixing key values.
* `pkg/router/template/configmanager/haproxy/backend.go` (`Backend`): Use `ServiceAliasConfigKey` for the name.
(`buildHAProxyBackends`, `newBackend`, `Name`, `ApplyChanges`): Adapt to use the new `ServiceAliasConfigKey` type.
* `pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go` (`fakeConfigManager`): Use `ServiceAliasConfigKey` for the `blueprints` map.
(`newFakeConfigManager`, `FindBlueprint`, `Register`, `AddRoute`, `RemoveRoute`, `ReplaceRouteEndpoints`, `RemoveRouteEndpoints`, `routeKey`):
* …

Add ServiceUnitKey and ServiceAliasConfigKey types

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

With extended validation enabled, if the router detects an ECDSA private key when processing TLS data,
the sanitized key output is rendered with PEM block headers like:
-----BEGIN ECDSA PARAMETERS-----
-----END ECDSA PARAMETERS-----
However, OpenSSL recognizes the following headers for ECDSA keys[1]:
-----BEGIN EC PARAMETERS-----
-----END EC PARAMETERS-----
Consequently, when the router provides haproxy with such PEM files through
`crt-list` option, haproxy (which uses OpenSSL) fails to load the key and reload
fails.
The impact is that a Route resource containing an ECDSA key in `.spec.tls.key`
will cause haproxy reloads to crash loop, preventing any further router
processing until the problematic Route is deleted.
This patch ensures that sanitized ECDSA key output follows the OpenSSL …

[release-4.2] Bug 1758373: fix haproxy reload crash when processing ECDSA keys

---

pkg/router/controller/hostindex/activation.go
pkg/router/controller/hostindex/hostindex_test.go

Ensure that a passthrough route displaces any path-based TLS routes with the same host, because passthrough is incompatible with path-based routing.
* `pkg/router/controller/hostindex/activation.go` (`hasExistingMatch`): Return true if both routes are TLS and the existing route is a passthrough route.
* `pkg/router/controller/hostindex/hostindex_test.go` (`Test_hostIndex`): Verify that a passthrough route displaces path-based TLS routes with the same host, but does not displace non-TLS routes.

Bug 1691190: hostindex: Passthrough displaces path-based TLS routes

---

pkg/router/controller/hostindex/activation.go
pkg/router/controller/hostindex/hostindex_test.go

Just as a passthrough route displaces any path-based TLS routes with the same host, a path-based TLS route displaces any passthrough route with the same host.
Follow-up to #57.
* `pkg/router/controller/hostindex/activation.go` (`hasExistingMatch`): Return true if both routes are TLS and *either* route is passthrough.
* `pkg/router/controller/hostindex/hostindex_test.go` (`Test_hostIndex`): Verify that a path-based TLS route displaces passthrough routes with the same host.

Bug 1691190: hostindex: Path-based TLS displaces passthrough

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

With extended validation enabled, if the router detects an ECDSA private key when processing TLS data,
the sanitized key output is rendered with PEM block headers like:
-----BEGIN ECDSA PARAMETERS-----
-----END ECDSA PARAMETERS-----
However, OpenSSL recognizes the following headers for ECDSA keys[1]:
-----BEGIN EC PARAMETERS-----
-----END EC PARAMETERS-----
Consequently, when the router provides haproxy with such PEM files through
`crt-list` option, haproxy (which uses OpenSSL) fails to load the key and reload
fails.
The impact is that a Route resource containing an ECDSA key in `.spec.tls.key`
will cause haproxy reloads to crash loop, preventing any further router
processing until the problematic Route is deleted.
This patch ensures that sanitized ECDSA key output follows the OpenSSL …

Bug 1758374: fix haproxy reload crash when processing ECDSA keys

---

pkg/cmd/infra/router/template.go

The metrics certificate can be rotated. Add support to dynamically reload
the certificate and key file when they change. This enables certificate
rotation without incurring an expensive restart.
Before this change, metrics scraping can begin failing when the metrics
endpoint's certificate is invalidated and can't be fixed without restarting
the controller.

Bug 1771783: Dynamically reload metrics certificate/key file changes

---

pkg/router/controller/unique_host.go
pkg/router/template/plugin_test.go

Change the unique_host plugin's `HandleRoute` method not to return an error because the host name is claimed.
Returning an error causes the controller to log an unhelpful error message:
router_controller.go:244] another route has claimed this host
The plugin already logs the conflict, along with the host name and the claimants' names and namespaces, at a higher log level and updates the Route's status to indicate that it has been rejected because of a preëmpting claim.  Moreover, a conflicting claim does not logically represent an error condition for the plugin or controller, and in the absence of such, it makes more sense return a nil error value after logging the condition.
* `pkg/router/controller/unique_host.go`: Do not return a gratuitous error value for a preëmpting claim.
* …

Bug 1780794: unique_host: HandleRoute: No error if host claimed

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel

Move to haproxy 2.x which is packaged here:
https://pkgs.devel.redhat.com/cgit/rpms/haproxy/log/?h=rhaos-4.4-rhel-7

images/router/haproxy: switch to haproxy 2.0

---

images/router/haproxy/conf/haproxy-config.template

PR #8 incorrectly double quoted the proto-version field value, even when this value was empty.  Per [rfc7230 section-3.2.6](https://tools.ietf.org/html/rfc7230#section-3.2.6), field values must consist of 1 character (`1*tchar`). During my investigation, I could not find any references for the `proto-version` header. This header appears to be unnecessary and is removed by this PR.
/assign @ironcladlou @Miciah

Bug 1803001: Removes Unneeded proto-version Header

---

images/router/haproxy/reload-haproxy
pkg/cmd/infra/router/template.go
pkg/router/metrics/health.go
pkg/router/shutdown/shutdown.go
pkg/router/shutdown/signal_posix.go
pkg/router/shutdown/signal_windows.go
pkg/router/template/limiter/limiter.go
pkg/router/template/plugin.go
pkg/router/template/router.go

Graceful shutdown in Kubernetes requires:
1. Wait for the frontend to be taken out of rotation by kube-proxy (fast, 5s or so) and external load balancers (slow, 45s is reasonable across all clouds) so that new connections are not allowed
2. Stop accepting new connections
3. Drain existing connections within some timeout
4. Exit with 0 if drain before the timeout, exit with 1 after the timeout (connections still outstanding) 
This PR updates the router to implement the above logic.
When the main process recieves SIGTERM or SIGINT, wait ROUTER_GRACEFUL_SHUTDOWN_DELAY (default: 45) seconds and then signal the reload script with ROUTER_SHUTDOWN=true that a graceful termination is requested. The reload-haproxy script then invokes USR1 on all child haproxy processes and waits …

Bug 1809665: Start graceful shutdown on SIGTERM

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/nginx/Dockerfile
images/router/nginx/Dockerfile.rhel

Docker treats /* as a "collapse subdirectory" option, so we should
avoid potentially incompatible behavior across multiple builders.

Bug 1810181: Wildcard is not needed to copy subdirectory in dockerfile

---

pkg/cmd/infra/router/template.go

Cherry-pick of #61. It didn't apply cleanly, the logging needed to be switched to glog for the release-4.2 branch.
/cc @ironcladlou

[release-4.2] Bug 1809398: Dynamically reload metrics certificate/key file changes

---

pkg/router/template/router.go

Set up a watch on the default certificate secret even if it does not contain a valid certificate when openshift-router starts.
https://jira.coreos.com/browse/NE-228

Bug 1820400: Watch default certificate secret even if initial secret is invalid

---

images/router/haproxy/conf/haproxy-config.template

Set the hostname field in the syslog header if syslog is configured.
* `images/router/haproxy/conf/haproxy-config.template` (`global`): Set `log-send-hostname`.

Set log-send-hostname in haproxy-config.template

---

Makefile
hack/verify-deps.sh
hack/verify-gofmt.sh
pkg/router/template/certmanager_test.go

Add verify build target that checks for:
- gofmt
- go module correctness
Ran `make verify` and fixed the one formatting change.

build: Add verify target

---

images/router/haproxy/conf/haproxy-config.template

Removes `alpn h2,http/1.1` from frontend `fe_sni` and `fe_no_sni`.

Bug 1825354: Removes ALPN from haproxy frontends

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper.go
pkg/router/template/util/haproxy/map_entry.go
pkg/router/template/util/haproxy/map_entry_test.go
pkg/router/template/util/haproxy/types.go

This change supports http/2 negotiation for re-encrypt and pass-through routes only. For a re-encrypt route, a custom certificate must be specified to enable http/2 negotiation through the router to the server backend. 
The original diagnosis was made in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1826990:
> In OpenShift 4.4, we enabled HTTP/2 on the frontend for the ingress controller; that is, we allow clients to ask the ingress controller to use HTTP/2, using ALPN.  Because the console and oauth-server are both behind the ingress controller's balancer and are using the same serving certificate (namely the ingress controller's default certificate), a browser might perform connection coalescing[1], meaning the browser re-uses the connection that it used to connect to the console …

Bug 1832352: Enable ALPN http/2 on reencrypt and passthrough routes only

---

go.mod
go.sum
pkg/router/metrics/haproxy/haproxy.go
pkg/router/metrics/haproxy/haproxy_test.go

Only a subset of metrics are supposed to have incremented values.
The current logic increments ALL values after restart.

Bug 1832539: Only a subset of router metrics should be preserved across restarts

---

pkg/router/metrics/haproxy/haproxy.go
pkg/router/metrics/haproxy/haproxy_test.go

A number of new metrics have been added to HAProxy that enable better insight into workloads.
The 1xx, 3xx, and 4xx counters will allow total request count to be assessed for non passthrough routes.
The queue and connect latency metrics will give visibility into moving window latency around overload and TLS termination latencies.
The reused connections metric will allow a rough breakdown of which services are experiencing connection churn.
The connections total metric is new and is more accurate than sessions, so use that for frontends.
Builds on top of #127
Fixes #81

Bug 1832629: Add metrics for 1xx, 3xx, and 4xx request counters, add latency, track reused connections

---

pkg/router/metrics/haproxy/haproxy.go

When no servers are exposed, backend metrics are needed to see how many requests are making it to a service. If we don't report them users can't see when no pods are up (a crashlooping service for instance would have no metrics at all because no pods are ready). Always report all backend
metrics. Increases cardinality by O(routes), but prometheus is a lot faster now and this should balance out.

Bug 1835845: Report all backend metrics for when there are no endpoints

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/router.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

This is to support the kill functionality added by:
https://github.com/openshift/cluster-ingress-operator/pull/401

Bug 1837251: Add unsupported http/2 kill switch

---

pkg/router/template/template_helper.go
pkg/router/template/util/haproxy/map_entry.go
pkg/router/template/util/haproxy/map_entry_test.go
pkg/router/template/util/haproxy/types.go

Delete superfluous conditions in the `cert_config.map` generation logic.
https://github.com/openshift/router/pull/125 modified the logic that generates entries in `cert_config.map` in order to add `[alpn h2,http/1.1]` stanzas, with the condition that the stanza was only added if the backend the corresponded to an entry had a certificate and specified edge or reencrypt termination.  However, the generation logic already only adds entries for backends that have certificates and specify either edge or reencrypt termination, so the additional condition is superfluous.
* `pkg/router/template/template_helper.go` (`generateHAProxyCertConfigMap`): Replace use of `SSLBindConfig` with a string literal.
* `pkg/router/template/util/haproxy/map_entry.go` (`generateCertConfigMapEntry`):
* …

Simplify generateCertConfigMapEntry

---

images/router/haproxy/conf/haproxy-config.template

cherry-picked changes from https://github.com/openshift/router/pull/90

Bug 1816540: [4.3] Backport "remove proto-version header field"

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

Modify the extended validation logic to copy any private key found in the certificate field of a route's TLS configuration to its key field.
Extended validation validates a route's TLS configuration using any key that is specified in either the TLS configuration's certificate field or its key field.  As a result, a route that specifies the certificate and key together in the certificate field may pass extended validation and be admitted.  However, before this commit, the certificate manager only wrote the certificate out if the TLS configuration had a nonempty key field.  As a result, a route with a valid certificate and key could be admitted but the certificate and key not written out, which would cause HAProxy to fail to load.
* `pkg/router/routeapihelpers/validation.go` …

Bug 1843856: Sanitize TLS config that has key bundled with cert

---

pkg/router/template/router.go
pkg/router/template/template_helper.go

Fix some lookups in the service alias configuration's certificates map to use `generateCertKey` instead of using the host as the map key.
* `pkg/router/template/router.go` (`hasRequiredEdgeCerts`):
* `pkg/router/template/template_helper.go` (`generateHAProxyCertConfigMap`): Use `generateCertKey` to get the map key for the certificate in the service alias configuration.

Use generateCertKey consistently

---

images/router/haproxy/conf/haproxy-config.template
pkg/cmd/infra/router/template.go
pkg/router/template/plugin.go
pkg/router/template/router.go
pkg/router/template/types.go

Add `--capture-http-request-headers` and `--capture-http-response-headers` command-line flags, as well as `ROUTER_CAPTURE_HTTP_REQUEST_HEADERS` and `ROUTER_CAPTURE_HTTP_RESPONSE_HEADERS` environment variables, to allow specifying HTTP request or response headers that should be captured for logging.
Each flag or environment variable accepts a comma-delimited list of `name:maxLength` values, where `name` is an HTTP header name and `maxLength` is a maximum length.  The router captures the named headers, which may be referenced in a custom `ROUTER_SYSLOG_FORMAT` string or are included in the default log message format if no custom format string is provided.  A header value that exceeds its maximum length is truncated to that length.
This change is related to …

Add HTTP header capture

---

pkg/router/router_test.go
pkg/router/template/router.go

Whilst looking at the existing unit tests we have for endpoints (because we plan to switch to endpoint slices) I noticed that the unit tests were not creating the config files when calling `writeConfig()`. Working back through the call chain it highlights that we ignore potential errors from `commitAndReload()`.
This correction now means the unit tests correctly write the config files in the temporary directories. But we may now see errors at runtime as they were previously masked.
I split the commits in two. The first just handles the unit tests, which I think we want anyway. The second commit just handles the case where we were ignoring the error.

Handle errors from commit and reload 

---

images/router/haproxy/conf/haproxy-config.template

Implement the `ROUTER_UNIQUE_ID_FORMAT` and `ROUTER_UNIQUE_ID_HEADER_NAME` environment variables, which may be used to specify that a header with the given name and format should be injected into every HTTP request.  This header can be used by the application or printed in access logs in order to facilitate tracing requests.
* `images/router/haproxy/conf/haproxy-config.template:` Add `unique-id-format` and `unique-id-header` stanzas using the values from the `ROUTER_UNIQUE_ID_FORMAT` and `ROUTER_UNIQUE_ID_HEADER_NAME` environment variables if the values are nonempty.

Allow configuring unique-id HTTP header

---

images/router/haproxy/conf/haproxy-config.template
pkg/cmd/infra/router/template.go
pkg/router/template/plugin.go
pkg/router/template/router.go
pkg/router/template/types.go

Add a `--capture-http-cookie` command-line flag, as well as `ROUTER_CAPTURE_HTTP_COOKIE` environment variable, to allow specifying an HTTP cookie that should be captured for logging.
The flag and environment variable each accept a `name:maxLength` value, where `name` is an HTTP cookie and `maxLength` is a maximum length.  The router captures the named cookie, which may be referenced in a custom `ROUTER_SYSLOG_FORMAT` string or is included in the default log message format if no custom format string is provided.  A cookie value that exceeds its maximum length is truncated to that length.  The value of the first cookie that matches the provided name captured.  By default, names are compared using a prefix match.  An equals sign ("=") may be appended to the name to indicate that the …

Add HTTP cookie capture

---

images/router/haproxy/conf/haproxy-config.template

Implement the `ROUTER_SET_FORWARDED_HEADERS` environment variable and `haproxy.router.openshift.io/set-forwarded-headers` route annotation.  The annotation takes precedence over the environment variable.  The environment variable and annotation may specify any of the following values to control when HAProxy sets the `Forwarded` and `X-Forwarded-*` headers:
* `append` to append to existing headers.
* `replace` to replace existing headers.
* `if-none` to set the headers if they are absent.
* `never` to never set headers.
The default setting is `append`.
* `images/router/haproxy/conf/haproxy-config.template`: Add a new variable, `setForwardedHeadersPattern`, with a regular expression that matches the values listed above.  Add a new variable,` `setForwardedHeadersAnnotation, with the new …

Allow configuring Forwarded/X-Forwarded-* headers

---

pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
pkg/router/template/configmanager/haproxy/manager.go
pkg/router/template/types.go

Following https://github.com/openshift/router/pull/51 doing it for other template methods.
Verified that the router is functional with these changes and `ROUTER_HAPROXY_CONFIG_MANAGER='true'`
Fixes #107

Use ServiceAliasConfigKeys for dynamic config

---

images/router/haproxy/Dockerfile.rhel8

A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.

Add Dockerfile.rhel8

---

pkg/cmd/infra/router/router.go
pkg/router/controller/endpointsubset/sort_address.go
pkg/router/controller/endpointsubset/sort_port.go
pkg/router/controller/factory/factory.go
pkg/router/controller/router_controller.go
pkg/router/template/plugin.go

Handle endpoint slices so that we can deal with dual-stack pods.
~~Needs: https://github.com/openshift/cluster-ingress-operator/pull/426~~ - now merged
~~Needs: https://github.com/openshift/openshift-apiserver/pull/125/~~ - now merged
https://github.com/openshift/cluster-ingress-operator/pull/428 allows us to turn on/off support for endpointslices via an ingresscontroller or the ingress config.

Switch to EndpointSlices

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/configmanager/haproxy/manager.go

Annotation is haproxy.router.openshift.io/rewrite-target
Fixes https://github.com/openshift/origin/issues/20474
documentation: https://github.com/openshift/openshift-docs/pull/22021
This feature is also related to this enhancement: https://github.com/openshift/enhancements/pull/287

feat(route): Implements rewrite-target for ha-proxy

---

pkg/router/template/router.go

Waiting for the router factory/controller to call the router plugin's `Commit` function guarantees that route/endpoint resources are available to the template code, and thus removes the possibility of a "routeless" router. A "routeless" router can be detrimental during upgrades if the routes carrying over during the upgrade break a newer version HAProxy, since the "routeless" configuration will continue to run if future successive reloads fail, and the upgrade will succeed when it should not.
The initial (premature) call to the router's `commitAndReload()` function outside of the rate limited loop is older code (3.11 era) and should be removed.  
This PR also adds a failed reload count metric for tracking failed reloads that happen well after a new router pod is created. This will be used …

Bug 1861455: Remove initial haproxy template commitAndReload

---

go.mod
go.sum
pkg/cmd/infra/router/template.go
pkg/router/controller/endpointsubset/sort_address.go
pkg/router/controller/endpointsubset/sort_address_test.go
pkg/router/controller/endpointsubset/sort_port.go
pkg/router/controller/endpointsubset/sort_port_test.go
pkg/router/controller/factory/factory.go
pkg/router/controller/factory/factory_endpointslices_test.go
pkg/router/controller/router_controller.go
pkg/router/router_test.go
vendor/github.com/fortytw2/leaktest/.travis.yml
vendor/github.com/fortytw2/leaktest/LICENSE
vendor/github.com/fortytw2/leaktest/README.md
vendor/github.com/fortytw2/leaktest/leaktest.go
vendor/modules.txt

Extends the unit tests to verify the behaviour of adding/deleting endpointslices.
Notable changes:
- Switches the service name label to the upstream definition
- Adds go routines leak checks in the new unit tests

Bug 1867971: extend unit tests for endpointslices

---

pkg/router/template/router.go

Back port of https://github.com/openshift/router/pull/165 as per BZ 1866454.
/assign @Miciah

[release-4.5] Bug 1866454: Back port Remove initial haproxy template commitAndReload

---

images/router/haproxy/Dockerfile.rhel8

Force openssl to use `SECLEVEL=1` to allow for 1024 bit RSA keys to be used in HAProxy for TLS. 
Relevant documentation:
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html
https://access.redhat.com/articles/3666211

Bug 1874278: Drop openssl to SECLEVEL=1 in Dockerfile

---

pkg/router/metrics/haproxy/haproxy.go
pkg/router/metrics/haproxy/haproxy_test.go

The HAProxy router [reload process calls](https://github.com/openshift/router/blob/master/pkg/cmd/infra/router/template.go#L539) `CollectNow()` in `pkg/router/metrics/haproxy/haproxy.go`. Currently, `CollectNow()` _does not_ update `e.lastScrape`, which means it is possible for the normal scrape function `Collect(...)` to be called _just after_ `CollectNow()`, but before HAProxy has actually reloaded, since `CollectNow()` essentially "resets" the metrics scrape interval.
The idea in this PR is to have `CollectNow()` set the `e.lastScrape` time, since `CollectNow()` is calling `scrape()` anyways. This will prevent counter metrics from decreasing across reloads since metrics are only saved for reload preservation during `CollectNow()` to minimize memory usage.

Bug 1752814: Fix decreasing counter metrics when reloading HAProxy

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/configmanager/haproxy/manager.go

Fix to add annotation for same site via route
Usage -> oc annotate route myapp router.openshift.io/cookie-same-site="Lax"|"Strict"|"None"
1. Setting Lax
[miheer@miheer ocp-4-6-samesite]$ oc annotate route myapp router.openshift.io/cookie-same-site="Lax" -n showcase --overwrite
route.route.openshift.io/myapp annotated
[miheer@miheer ocp-4-6-samesite]$ curl -vk https://www.examplesite1.apps.misalunk-rfe600.apacshift.support
< date: Tue, 22 Sep 2020 17:07:06 GMT
* Added cookie 87ab708e9d309ffdd16273918fdaf28c="cdd92fe93ea53dbca50353a813393b52" for domain www.examplesite1.apps.misalunk-rfe600.apacshift.support, path /, expire 0
< set-cookie: 87ab708e9d309ffdd16273918fdaf28c=cdd92fe93ea53dbca50353a813393b52; path=/; HttpOnly; Secure; SameSite=Lax
< cache-control: private
* HTTP/1.0 connection …

Bug 1867186: Add SameSite route annotation

---

images/router/haproxy/conf/haproxy-config.template

Enable HTX if HTTP/2 is enabled, and turn off HTX otherwise.  Enabling HTX causes HAProxy to down-case HTTP header names, which breaks non-conformant legacy HTTP clients and servers.
* `images/router/haproxy/conf/haproxy-config.template`: Turn off HTX if HTTP/2 is not enabled.

Bug 1885414: haproxy-config.template: Only enable HTX for HTTP/2

---

images/router/base/Dockerfile.rhel

Updating ose-haproxy-router-base builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-haproxy-router-base.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-haproxy-router-base builder & base images to be consistent with ART

---

images/router/haproxy/Dockerfile.rhel8

Updating openshift-enterprise-haproxy-router builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-haproxy-router.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/router/pull/197 . Allow it to merge and then run `/test all` on this PR.

Updating openshift-enterprise-haproxy-router builder & base images to be consistent with ART

---

images/router/haproxy/conf/haproxy-config.template

Implement the `ROUTER_DONT_LOG_NULL` and `ROUTER_HTTP_IGNORE_PROBES` environment variables, which control HAProxy's `dontlognull` and `http-ignore-probes` options.
* `images/router/haproxy/conf/haproxy-config.template`: Add `ROUTER_DONT_LOG_NULL` and `ROUTER_HTTP_IGNORE_PROBES`.
----
Related to https://github.com/openshift/enhancements/pull/460.

Allow configuring dontlognull/http-ignore-probes

---

pkg/cmd/infra/router/router.go

Fix the log output of any configured namespace label selectors on startup.
With `NAMESPACE_LABELS` set to `foo=bar`, before this change, the output looked like this:
"msg"="router is only using routes in namespaces matching labels"  "labels"=[{}]
After this change, the output looks like this:
"msg"="router is only using routes in namespaces matching labels"  "labels"="foo=bar"
Most likely the output was broken by the change from glog to logr/zap in https://github.com/openshift/router/pull/47/commits/dc68ebfcbd9fdc600391ebe050228534dd2b07c3.
* `pkg/cmd/infra/router/router.go` (`NewFactory`): Stringify label selectors before logging them.

Bug 1889863: Fix logging of namespace label selector

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

As haproxy22 is now in:
http://download.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/plashets/4.7-el8/building/
bump to consume the haproxy22 package otherwise all builds will currently fail.

images/router: Update to haproxy22 package

---

pkg/router/template/router.go

pkg/router/template/router.go: Replace the current template_router_reload_fails counter metric with a new gauge metric, titled template_router_reload_failure, that tracks the result of the most recent HAProxy reload. If a reload fails, the template_router_reload_failure metric will be set to 1 until a successful reload sets the metric to 0.
Previously, the template_router_reload_fails counter metric would monotonically increase when an HAProxy reload failed. This counter metric is difficult to alert on since an increasing counter essentially gives no indication that the reload failures have been resolved.
This new boolean based metric is trivial to properly alert on since the metric will hold "1" if and only if the router is _not_ successfully reloading.

Bug 1892338: metrics: Rework template_router_reload_failure metric

---

pkg/router/controller/contention.go
pkg/router/controller/status.go
pkg/router/template/router.go
pkg/router/template/template_helper.go

$ gosec -version
Version: 2.5.0
Git tag: v2.5.0
Build date: 2020-10-26T11:52:22Z
On simple inspection the G601 issues from gosec looked innocuous
enough but I decided to clean these up anyway.
For the changes to router.go and template_helper.go I took the
simplest approach of creating a new variable (and copy). I could have
changed everything to be index based but I chose to go with the
smallest change.
PR inspired by https://github.com/openshift/router/issues/208
It still leaves open the question asked in #208 on whether we will run
this tool as during build and/or prior to a release.

Address gosec G601 issues

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

This PR adds the function `clipHAProxyTimeoutValue(...)` to `pkg/router/template/template_helper.go` to prevent invalid Route timeout annotations from breaking router reloads. In version 2.x, HAProxy supports a maximum timeout of `2147483647ms`, which is ~24.8 days. `clipHAProxyTimeoutValue` will replace any timeout above the maximum amount with the maximum allowable amount to prevent HAProxy from crashing after upgrades that bump HAProxy 1.8 to 2.x.
This PR also adds unit tests cases for `clipHAProxyTimeoutValue` to verify that it works as intended.

Bug 1861383: Clip haproxy.router.openshift.io/timeout annotation values to prevent bricking on upgrade

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

This reverts commit 5f30097fb56585065e5c480272f48222497f1e38.
haproxy-2.2.4 will not allow us to disable HTX anymore which means
client/servers will get down-cased headers. As this may break
customers upgrading from OpenShift 4.6 => 4.7 we plan to add an API in
4.7 that will allow customers to specify case adjustment for various
routes. With that knob in place we will target 2.2.x for OpenShift
4.8.
https://github.com/openshift/enhancements/pull/550

Revert "images/router: Update to haproxy22 package"

---

pkg/router/controller/router_controller.go

When aggregating endpointslices check the Ready condition status. If
it is not ready then accumulate those addresses into the
NotReadyAddresses bucket. Although the router doesn't actually
use NotReadyAddresses we set this to have a faithful and technically
correct translation of EndpointSlices to Endpoints.
EndpointSlices were introduced in 4.6: see #154 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1903206

Bug 1903206: Check Ready condition status in Endpointslices

---

images/router/haproxy/conf/haproxy-config.template
pkg/cmd/infra/router/template.go
pkg/router/template/plugin.go
pkg/router/template/router.go
pkg/router/template/types.go

Implement the `--http-header-name-case-adjustments` flag and `ROUTER_H1_CASE_ADJUST` environment variable to allow specifying case adjustments for HTTP header names.
* `images/router/haproxy/conf/haproxy-config.template`: Add `option h1-case-adjust-bogus-client` and `h1-case-adjust` settings to the global configuration if any adjustments are specified.  Add `option h1-case-adjust-bogus-server` settings to routes that have the `haproxy.router.openshift.io/h1-adjust-case` annotation.
* `pkg/cmd/infra/router/template.go` (`TemplateRouter`): Add `HTTPHeaderNameCaseAdjustmentsString` and `HTTPHeaderNameCaseAdjustment` fields.
(`Bind`): Add `--http-header-name-case-adjustments,` which defaults to the value of the `ROUTER`_H1_CASE_ADJUST environment variable. …

Allow configuring HTTP header name case adjustment

---

pkg/router/controller/endpointsubset/converter.go
pkg/router/controller/endpointsubset/converter_test.go
pkg/router/controller/router_controller.go

Moved the existing utility function into endpointsubset package. Added
unit tests to assert on EndpointSlices having Ready/NotReady
conditions.
Follow on from https://github.com/openshift/router/pull/229

Bug 1903206: Add unit tests to verify NotReadyAddresses in EndpointSlices

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

This is the 4.5 back port of https://github.com/openshift/router/pull/196
---
This PR adds the function `clipHAProxyTimeoutValue(...)` to `pkg/router/template/template_helper.go` to prevent invalid Route timeout annotations from breaking router reloads. In version 2.x, HAProxy supports a maximum timeout of `2147483647ms`, which is ~24.8 days. `clipHAProxyTimeoutValue` will replace any timeout above the maximum amount with the maximum allowable amount to prevent HAProxy from crashing after upgrades that bump HAProxy 1.8 to 2.x.
This PR also adds unit tests cases for `clipHAProxyTimeoutValue` to verify that it works as intended.

[release-4.5] Bug 1896914: Back port Clip haproxy.router.openshift.io/timeout annotation values to prevent bricking on upgrade

---

images/router/haproxy/conf/haproxy-config.template

Turn off HTX.  Enabling HTX causes HAProxy to down-case HTTP header names, which breaks non-conformant legacy HTTP clients and servers.  HTTP/2 requires HTX, but OpenShift 4.4 does not support HTTP/2.
* `images/router/haproxy/conf/haproxy-config.template`: Turn off HTX.
----
This PR supersedes https://github.com/openshift/router/pull/201.

[release-4.4] Bug 1886215: haproxy-config.template: Turn off HTX

---

images/router/haproxy/conf/haproxy-config.template

The existing annotation "haproxy.router.openshift.io/timeout" affects
"timeout server" for cleartext/edge/reencrypt routes and "timeout
tunnel" for passthrough routes.
If your cleartext/edge/reencrypt route is upgraded to become a
tunnel (e.g., a websocket) then your backend will get the global
default ROUTER_DEFAULT_TUNNEL_TIMEOUT for "timeout tunnel" which is
unexpected and possibly a vastly different value given that the
default is 1 hour.
From the haproxy-2.0 docs:
```
If some long-lived sessions are mixed with short-lived sessions (e.g.
WebSocket and HTTP), it's worth considering "timeout tunnel", which
overrides "timeout client" and "timeout server" for tunnels.
This timeout supersedes both the client and server timeouts once the
connection becomes a tunnel.
```
This commit enables …

Bug 1905100: Add tunnel-timeout and hard-stop-after options to haproxy template

---

pkg/router/template/router.go
pkg/router/template/router_test.go

If the router instance is sharded then ensure that unrelated endpoint
changes (add/delete) don't cause the router to reload unnecessarily.

Bug 1905748: Prevent unnecessary reloads in router shards

---

pkg/router/template/plugin.go

As we have moved to endpointslices we now check the service for the
idled annotation. `oc idle` has been updated to annotate the service.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1900989

Bug 1900989: Move idle check from endpoints to service

---

images/router/haproxy/conf/haproxy-config.template

Do not put brackets around an IPv4 address in the Forwarded header. [RFC 7239](https://tools.ietf.org/html/rfc7239) dictates that the host name in the header should be an IPv4 address (without brackets) or an IPv6 address with brackets.
* `images/router/haproxy/conf/haproxy-config.template`: Don't quote IPv4 addresses in v4v6 mode.
----
Not thoroughly tested as I do not have an IPv6 cluster.

Bug 1801407: Omit brackets around IPv4 addresses in v4v6 mode

---

images/router/haproxy/conf/haproxy-config.template

Commit 8580700 bumped the HAProxy version of the router
to v2.2. In HAProxy 2.2, the `http-use-htx` option is deprecated.
Commit da09224 added configurable HTTP header case names to the router.
With commits da09224 and 8580700 in place, we can safely remove the
`http-use-htx` option (and thus silence any HAProxy warnings about it's
deprecation).

template: Drop http-use-htx option

---

pkg/router/controller/contention.go
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/golang.org/x/xerrors/LICENSE
vendor/golang.org/x/xerrors/PATENTS
vendor/golang.org/x/xerrors/README
vendor/golang.org/x/xerrors/adaptor.go
vendor/golang.org/x/xerrors/codereview.cfg
vendor/golang.org/x/xerrors/doc.go
vendor/golang.org/x/xerrors/errors.go
vendor/golang.org/x/xerrors/fmt.go
vendor/golang.org/x/xerrors/format.go
vendor/golang.org/x/xerrors/frame.go
vendor/golang.org/x/xerrors/go.mod
vendor/golang.org/x/xerrors/internal/internal.go
vendor/golang.org/x/xerrors/wrap.go
vendor/modules.txt

**contention: Contend over route ingress admission condition **
pkg/router/controller/contention.go: Enhance `ingressEqual` to compare
the given route ingress' admission condition, ignoring transition
times. This is to remedy situations where router replicas disagree
explicitly on an ingress admission condition for a route when no changes
to a route's spec or status (excluding status.conditions) are made,
such as when an ingress controller switches from a `namespaceOwnership`
policy of `InterNamespaceAllowed` to `Strict`.
vendor: pull in go-cmp/cmp/cmpopts source.
(go-cmp is already in go.mod)

Bug 1903821: contention: Contend over route ingress admission condition 

---

pkg/router/metrics/metrics.go
pkg/router/shutdown/shutdown.go

Before this PR, the metrics listener code panicked on errors.  This PR changes the listener code to log the error and shut down the router gracefully when an error is encountered.
* `pkg/router/shutdown/shutdown.go` (`RequestShutdown`): New function.  Trigger shutdown by sending a the shutdown handler a fake signal.
* `pkg/router/metrics/metrics.go` (`Listen`): Log errors, and use the new `RequestShutdown` function to initiate graceful shutdown if the metrics listener fails, instead of panicking on errors.

Bug 1909906: Exit gracefully if metrics listener fails

---

pkg/router/template/router.go
pkg/router/template/template_helper.go

This is an optimisation that caches compiled regular expressions.
When the template is written calls to `matchString` and `firstMatch`
would recompile the regular expression on every call. When you are
processing ~13,000 routes the time to compile on each invocation becomes
significant. This change brings a reduction of 60% when processing and
writing `haproxy.config`.
```console
router.go:456] template "msg"="writeConfig"  "duration"="10.663160501s"
router.go:456] template "msg"="writeConfig"  "duration"="10.328840858s"
router.go:456] template "msg"="writeConfig"  "duration"="10.762876672s"
```
And if we cache the REs:
```console
template "msg"="writeConfig"  "duration"="3.659229627s"
template "msg"="writeConfig"  "duration"="3.718457818s"
template "msg"="writeConfig" …
```

Bug 1937972: router/template: Cache compiled regular expressions

---

images/router/haproxy/conf/haproxy-config.template

Allow configuring HAProxy header buffer sizes
Implement the `ROUTER_MAX_REWRITE_SIZE` & `ROUTER_BUF_SIZE` variables to enable control over HAProxy's tune.bufsize and tune.maxrewrite values.
images/router/haproxy/conf/haproxy-config.template: Add `ROUTER_MAX_REWRITE_SIZE` & `ROUTER_BUF_SIZE` env variables to the router template. Use previously fixed values (8192 and 32768 respectively) as defaults.
---
This is in support of https://issues.redhat.com/browse/NE-417.

NE-417: Allow configuring HAProxy header buffer sizes

---

pkg/router/controller/unique_host.go
pkg/router/controller/unique_host_test.go

The override annotation was supposed to allow a route to be created, but not admitted, if it had an invalid host name. However, use of the override now allows the route to be admitted with an invalid host name. Fix this so the route will not be admitted with an invalid host name.

Bug 1925697: Route admission should not use the override

---

pkg/router/controller/unique_host.go
pkg/router/controller/unique_host_test.go

The override added to address https://bugzilla.redhat.com/show_bug.cgi?id=1896977 was supposed to allow a route to be created, but not admitted, if it had an invalid host name.  However, it allows the route to be admitted with an invalid host name.  This fixes that.

Bug 1942534: [4.7 backport] Route gets admitted with invalid host name if override annotation is used

---

images/router/haproxy/conf/haproxy-config.template

Use consistent indentation for the HAProxy configuration template.  Note that the HAProxy configuration stanzas and the Go template stanzas are interpolated but have different indentation, which can be confusing but should be less confusing if the Go template indentation is consistent.
* `images/router/haproxy/conf/haproxy-config.template`: Re-indent Go template
actions.
---
I used [a quick-and-dirty AWK script ](https://gist.github.com/Miciah/8a2d5245ba8150a626acb16a16926021) to re-indent the template.  If this seems like a good idea, we could add some automated verification to make sure the Go template stanzas are consistently indented.

haproxy-config.template: Re-indent.

---

images/router/haproxy/conf/haproxy-config.template

* `images/router/haproxy/conf/haproxy-config.template`: Add a new variable, `balanceAlgoPattern`, with a regular expression that matches the allowed balancing algorithm names, and use it in backend stanzas.
Use the roundrobin balancing algorithm instead of using the algorithm specified by `ROUTER_LOAD_BALANCE_ALGORITHM` or `ROUTER_TCP_BALANCE_SCHEME` if the route has multiple services that specify weights.
Only the roundrobin algorithm properly handles weights, so if the route has multiple services that specify weights, roundrobin should be used unless the route has an explicit annotation that specifies a different algorithm for that specific route.
* `images/router/haproxy/conf/haproxy-config.template`: Use the roundrobin balancing algorithm if the service alias has multiple service …

haproxy-config.template: Use power-of-two balancing

---

pkg/router/controller/endpointsubset/converter.go
pkg/router/controller/endpointsubset/converter_test.go
pkg/router/controller/factory/factory.go
pkg/router/controller/factory/factory_endpointslices_test.go
pkg/router/controller/router_controller.go

Discovery.k8s.io/v1beta1 EndpointSlices are deprecated in favor of
discovery.k8s.io/v1 in Kubernetes 1.21.
pkg/router/controller/factory/factory.go &
pkg/router/controller/endpointsubset/converter.go &
pkg/router/controller/endpointsubset/converter_test.go &
pkg/router/controller/factory/factory_endpointslices_test.go:
Import `discoveryv1` and `corev1` explicitly. Update calling sites.
Update inline EndpointSlice resource API Version and Kind fields.
Update kube client API calls to use `discoveryv1`.

Bug 1947478: Switch from discovery v1beta1 to discovery v1

---

pkg/router/template/plugin.go

* Description: EndpointSlice can be duplicated. For suppressing broken haproxy.config, add a condition to check if the Endpoints is duplicated before adding the new endpoints actually.
* Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1961550

Bug 1961550: Add a condition to check if the Endpoints ID is duplicated

---

pkg/router/router_test.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

Fix for the following error: 
```
error executing template for file /tmp/router004931081/conf/haproxy.config: template: haproxy-config.template:492:84: executing "conf/haproxy.config" at <$cfgIdx>: wrong type for value; expected string; got templaterouter.ServiceAliasConfigKey
```
It happens when the whitelist of IPs has to be put into a file due to [the limitation of HAProxy config](https://github.com/openshift/router/blob/master/pkg/router/template/util/haproxy/whitelist.go#L11).

Bug 1964486:  template helper - generateHAProxyWhiteListFile, use right arg type

---

images/router/haproxy/conf/error-page-404.http
images/router/haproxy/conf/error-page-503.http
images/router/nginx/conf/error-page-503.html

@sg00dwin proposed me new CSS which they are using for the management console. It's based on PatternFly4 which is not using bootstrap and normalize.css anymore.
This is [how 503 page looked before](https://codepen.io/alebedev87/pen/NWpBGdP).
This is [how it looks now.](https://codepen.io/alebedev87/pen/bGqjVEX).
This is [how 404 page looks now](https://codepen.io/alebedev87/pen/mdWjJKL).
Note that nginx 503 page was not using CRLF, I kept it this way.

Bug 1967228: error pages - don't use bootstrap/normalize

---

HACKING.md
hack/Dockerfile.debug
hack/Makefile.debug

This commit adds 2 new "hacking" files, `hack/Dockerfile.debug`
and `hack/Makefile.debug`, as well as a new `HACKING.md` readme file.
Note that the files and instructions provided in this commit are
intended for Router development and are not officially supported
or guaranteed to work.

Hack: Add initial hacking instructions

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go

This PR makes HAProxy's config template accept HSTS headers with case insensitive directives and white spaces as stated in [RFC6797](https://datatracker.ietf.org/doc/html/rfc6797#section-6.1).
Apart from the unit test, tested manually:
```bash
$ oc get route console
NAME      HOST/PORT                                    PATH   SERVICES   PORT    TERMINATION          WILDCARD
console   console-openshift-console.apps-crc.testing          console    https   reencrypt/Redirect   None
$ oc get route console --template='{{$a := index .metadata.annotations "haproxy.router.openshift.io/hsts_header"}}{{$a}}{{"\n"}}'
MAX-age=99999 ;   includesubdomains;   Preload
$ curl -k -is https://console-openshift-console.apps-crc.testing | grep -i strict-transport
strict-transport-security: MAX-age=99999 ; …
```

Bug 1953113: template config - HSTS header's pattern accepts case insensitive and white spaces

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

New template helper to parse a list of IPs/CIDRs for the whitelisting.
Takes a different approach than https://github.com/openshift/router/pull/262 which uses a long regexp for IPv6 IPs/CIDRs.
The new function aims to keep the same behavior as the previous approach hence some corner cases (i.e. leading/trailing spaces).

Bug 1964482: config template: accept IPv6 IPs for whitelisting

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

This partially reverts PR #313. 
We are switching back to haproxy-2.2 as our performance analysis shows
there are performance degradations when compared to the haproxy-2.2
series.

Revert to haproxy22

---

images/router/haproxy/reload-haproxy

Use Curl's built-in support for PROXY protocol to replace the use of socat in the reload-haproxy script.  The router image has included a version of Curl that supports PROXY protocol for a while now.
* `images/router/haproxy/reload-haproxy`: Use curl `--haproxy-protocol` instead of socat when PROXY protocol is enabled.

reload-haproxy: Use curl --haproxy-protocol

---

pkg/router/template/router.go

* `pkg/router/template/router.go` (`watchSecretDir`): Use `log.Error` instead of `log.Info` when logging errors.
* `pkg/router/template/router.go` (`watchSecretDir`): Simplify by directly registering the change to trigger a router reload.
* `pkg/router/template/router.go` (`watchSecretDir`): Improve log messages for fsnotify events to indicate that they are coming from fsnotify and to show the operation and file path more clearly.
* `pkg/router/template/router.go` (`watchSecretDir`): Rename...
(`watchVolumeMountDir`): ...to this.  Factor out the logic specific to the default certificate.  Instead, take a path to a volume mount and a callback function, configure fsnotify to watch the `..data` symlink in the volume mount, and call the function when fsnotify sends an event if the symlink has …

Reload client CA and CRL when updated

---

images/router/haproxy/conf/haproxy-config.template

ROUTER_INSPECT_DELAY controls how long HAProxy can hold packets for inspection before it must forward to a backend. If unset, default inspect delay is 5s

NE-412: Add ROUTER_INSPECT_DELAY

---

images/router/haproxy/conf/haproxy-config.template

If the `ROUTER_MAX_CONNECTIONS` environment variable is not set, omit the `maxconn` option in the generated `haproxy.config` file.
HAProxy 2.2 and later compute a default value for maxconn based on the value of `ulimit -n`, which leaves performance tuning and handling of resource exhaustion to the platform where it belongs.
* `images/router/haproxy/conf/haproxy-config.template`: Omit `maxconn` if `ROUTER_MAX_CONNECTIONS` is empty or unset.

haproxy-config.template: Make maxconn optional

---

images/router/haproxy/conf/haproxy-config.template

If `ROUTER_INSPECT_DELAY` does not match `$timeSpecPattern`, fall back to the default value

Bug 1987238: Validate ROUTER_INSPECT_DELAY env value generating haproxy config

---

images/router/haproxy/conf/haproxy-config.template

Update the set of allowed balancing algorithms to include "random", i.e., the "Power of Two Random Choices" algorithm.  An earlier change was supposed to make "random" the default algorithm but failed to add it to the set of allowed algorithms.  As a result, the template would configure HAProxy to the "roundrobin" algorithm by default.  This change makes it so the effective default is "random", as intended in the earlier change.
Follow-up to https://github.com/openshift/router/pull/192/commits/dbc994cd367c1d162772a189d969d64d0b8f1341.
* `images/router/haproxy/conf/haproxy-config.template`: Fix `$balanceAlgoPattern` to match "random".
---
/cherry-pick release-4.8

Bug 1988801: haproxy-config.template: Fix power-of-two balancing

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

Bug 1994645: config template: accept IPv6 IPs for whitelisting

---

images/router/haproxy/conf/haproxy-config.template

Use Unix sockets instead of TCP sockets to connect the `be_sni` backend to the `fe_sni` frontend and the `be_no_sni` backend to the `fe_no_sni` frontend.
This change avoids the need for dedicated TCP ports.  It might also have a beneficial effect on performance.
* `images/router/haproxy/conf/haproxy-config.template`: Use Unix sockets instead of TCP sockets for the `be_sni`, `fe_sni`, `be_no_sni`, and `fe_no_sni` frontends and backends.

haproxy-config.template: Use Unix sockets

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper_test.go
pkg/router/template/util/haproxy/map_entry.go
pkg/router/template/util/haproxy/map_entry_test.go

Bug 2002205 - HTTPS redirect happens even if there is a more specific http-only route
Let's say we have 2 routes like this:
- HTTP-only route for "myapp.apps.example.com" domain and "/mypath" path
- HTTPS-edge-redirect route for "myapp.apps.example.com" and no path
In such situation, redirect is sent for any query to "myapp.apps.example.com", including "myapp.apps.example.com/mypath", so the more specific path route is not taking precedence as expected.

Bug 1896474:   HTTPS redirect happens even if there is a more specific http-only route

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/configmanager/haproxy/backend.go
pkg/router/template/configmanager/haproxy/manager.go
pkg/router/template/plugin.go
pkg/router/template/plugin_test.go
pkg/router/template/router.go
pkg/router/template/types.go

* `pkg/router/template/plugin_test.go` (`TestHandleTCPEndpoints`):
* `pkg/router/template/router.go` (`createServiceUnitInternal`): Fix typos in the godoc for these functions.
Check the `appProtocol` field on ports in Kubernetes `Endpoints` objects.  If the route is a reencrypt route with `appProtocol` "h2" or a non-TLS or edge-terminated route with `appProtocol` "h2c", configure HAProxy to use HTTP/2 for the endpoint.
Add checks in the dynamic config manager to force a full reload when a new endpoint specifies `appProtocol: h2` or `appProtocol: h2c` or an existing endpoint is modified to change it to or from specifying one of these appProtocol values on a port.  Dynamically configuring such an endpoint would require a way to set proto on the HAProxy server, and HAProxy's management …

Bug 1826225: Support edge-terminated h2 connections

---

pkg/router/template/router.go
pkg/router/template/router_test.go

Before this change, if the administrator provided a default certificate that was missing the newline character for the last line, the router would write out a corrupt PEM file for HAProxy, causing HAProxy to fail to start. This change adds logic to add the missing newline character to an incomplete line when writing out the PEM file.  As a result, the router now writes out a valid PEM file so that HAProxy can start even if the input is missing a newline character.
* `pkg/router/template/router.go` (`secretToPem`): Check for missing newline characters and add them if needed.
* `pkg/router/template/router_test.go` (`testWildcardCertificate`, `testWildcardCertificateKey`): New consts.
(`TestSecretToPem`): Verify that `secretToPem` writes out the expected PEM file.

Bug 1894431: Add missing newlines to default certificate and key

---

pkg/router/metrics/metrics.go

Call `os.Exit(1)` in the metrics `Listen` method if `net.Listen` fails (for example, because the stats port is already taken) so that the user immediately gets a nonzero exit code with a clear error message indicating that OpenShift router failed to start and why.
Before this change, the metrics `Listen` method called `shutdown.RequestShutdown()` when `net.Listen` returned an error.  This approach has at least four issues:
* Calling `shutdown.RequestShutdown()` doesn't cause the `Listen` method to return, so it continues to set up a cmux etc. with a nil value for `tcpl`,which causes cmux eventually to segfault.  (This is an issue only with the first call to `RequestShutdown` in the `Listen` method; the other calls to `RequestShutdown` are inside goroutines that already return immediately …

Bug 1909906: Exit immediately if stats port is taken

---

pkg/cmd/infra/router/template.go

Ingress router metrics endpoint was still serving old certificates after certificate rotation. This fixes the logic to reload the certificate when there is a change.

Bug 2025624: Fix certificate reloader

---

pkg/router/controller/factory/factory.go

If you quickly start and send a SIGTERM to the router, it will hang indefinitely.
The call to WaitForCacheSync wasn't listening for a SIGTERM and wouldn't terminate
if still trying to sync cache.

Bug 2076297: Fix gap in router's handling of graceful shutdowns.

---

pkg/router/template/router.go
pkg/router/template/router_test.go

Change to not scale weight to 256 if there is only one service for the route. More information can be found here: [NE-709 Impact of Server Weight on Memory Allocation](https://docs.google.com/document/d/1QX7GpJTWTpBAga4TMrshDCi5mHAd-4-IizcQS1CCMS4/edit)
In a nutshell, scaling the weight to 256 is redundant for single services routes since all servers in the haproxy backend will always have the same weight, so therefore weight 1 == weight 256. Reducing the weight helps with reducing the static memory allocation.

NE-822 Don't scale route weight on single service routes

---

images/router/haproxy/conf/haproxy-config.template

Previously, the `accept-proxy` directive (which enables HAProxy to
listen for PROXY protocol instead of regular HTTP traffic) was only
appended to the last entry in the section.
This worked fine for the IPv4 or IPv6 single-stack use-case, but not
for the dual-stack use-case. The following configuration is generated,
which means HAProxy listens for HTTP traffic via IPv4 and PROXY
protocol traffic via IPv6:
> bind :80
> bind :::80 v6only accept-proxy
This patch corrects the behavior such that the following configuration
is generated, where HAProxy correctly listens for PROXY protocol on
IPv4 and IPv6:
> bind :80 accept-proxy
> bind :::80 v6only accept-proxy
Signed-off-by: Jack Henschel <jackdev@mailbox.org>

Bug 2093454: HAProxy: enable PROXY protocol for all listeners

---

images/router/haproxy/conf/haproxy-config.template

This change increases the maximum number of simultaneous connections
that HAProxy will accommodate to 50000. This change will improve
router throughput at the expense of a modest increase in memory usage.
Using the following parameters we see a 3MB increase per-process.
```
maxconn  maxconn (HAProxy)  maxsock (HAProxy)  Process Size (MB)
-------  -----------------  -----------------  -----------------
2000               2000               4054                 53
20000              20000              40054                 56
50000              50000             100054                 59
100000             100000             200054                 66
200000             200000             400054                 78
auto             524261            1048576                119
```
And with 64 …

NE-1071: Default HAProxy maxconn value to 50000 for OCP 4.12

---

Makefile

CGO_ENABLED=1 is enabled to enable FIPS compliance through the C code that makes Cryptographic calls on Linux.
Added to Makefile
Link to [cluster-ingress-operator PR 833](https://github.com/openshift/cluster-ingress-operator/pull/833)
Signed-off-by: Paul Bastide <pbastide@redhat.com>

Bug 2107462: Update CGO_ENABLED=1

---

.ci-operator.yaml
images/router/base/Dockerfile.rhel
pkg/cmd/infra/router/template.go
pkg/router/controller/unique_host.go
pkg/router/metrics/health.go
pkg/router/template/certmanager_test.go
pkg/router/template/plugin.go
pkg/router/template/router.go
pkg/router/template/types.go

Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-haproxy-router-base.yml
This PR is based on #422 but additionally includes formatting changes to several files to appease gofmt.  Including these changes is necessary in order for the verify job to pass.

Updating ose-haproxy-router-base images to be consistent with ART

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

Update dockerfiles to use generic `haproxy` opposed to `haproxy22` so that the next container builds will use haproxy 2.6 which has been built via brew and checked in.
This will force the router to start using haproxy 2.6.

NE-1115: Update haproxy container builds to use haproxy 2.6

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

Reverting from haproxy26 to haproxy22 due to regression finding in OCPBUGS-10003.
`images/router/haproxy/Dockerfile`:
`images/router/haproxy/Dockerfile.rhel`:
`images/router/haproxy/Dockerfile.rhel8`: Update to haproxy 22 RPM in dockerfiles
Note: This will need to be timed with the rhpkg push and rhpkg build. Once the new haproxy RPM is pushed, then mirrored (takes up to 24 hours), builds for this repo will start failing (haproxy26 rpm will be removed) and this PR will need to be merged.

OCPBUGS-10003: Revert "NE-1115: Update haproxy container builds to use haproxy 2.6"

---

images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8

Reverts openshift/router#466
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
* This change is breaking ci 4.14 or nightly 4.14 payloads:
* https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-04-09-091435 
* https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade/1644993213582282752 
* This test breaks some functionality or is a regression
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and …

OCPBUGS-11595: Revert "[NE-1267] container builds: switch to haproxy26 package"

---

hack/generate-placeholder-crl.sh
hack/placeholder-ca.cnf.template
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8
images/router/haproxy/conf/haproxy-config.template
pkg/router/crl/crl.go
pkg/router/template/router.go
pkg/util/util.go

This PR makes the router parse the certificates supplied in ROUTER_MUTUAL_TLS_AUTH_CA, download CRLs from any CRL distribution points that are found, and write them to a file that is supplied to HAProxy for mTLS certificate validation.
It also includes a fix for an issue where, when a CRL is distributed in a certificate that is not its issuer, the CRL would sometimes be missing or two copies of the CRL would be present.

 OCPBUGS-6661, OCPBUGS-9464: Handle mTLS CRLs, and fix accidental CRL duplication

---

hack/generate-placeholder-crl.sh
hack/placeholder-ca.cnf.template
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8
images/router/haproxy/conf/haproxy-config.template
pkg/router/crl/crl.go
pkg/router/template/router.go
pkg/util/util.go

Manual cherry-pick of #472 
---
This PR makes the router parse the certificates supplied in ROUTER_MUTUAL_TLS_AUTH_CA, download CRLs from any CRL distribution points that are found, and write them to a file that is supplied to HAProxy for mTLS certificate validation.
It also includes a fix for an issue where, when a CRL is distributed in a certificate that is not its issuer, the CRL would sometimes be missing or two copies of the CRL would be present.

[release-4.11] OCPBUGS-14456, OCPBUGS-14457: Handle mTLS CRLs, and fix accidental CRL duplication

---

images/router/haproxy/conf/haproxy-config.template

When access logging is enabled, the user may specify a cookie to log. If the user specifies the length as longer than `tune.http.cookielen` (or 63 bytes if `tune.http.cookielen` is unset), it will be truncated. This PR sets `tune.http.cookielen` to an appropriate value when the capture cookie length would not fit in the default `tune.http.cookielen` size.

OCPBUGS-3356: Add support for tuning tune.http.cookielen

---

images/router/haproxy/conf/haproxy-config.template

Mitigation rule taken from the HAProxy 2.6.15 release announcement:
https://www.mail-archive.com/haproxy@formilux.org/msg43864.html
And quoting from the release notes:
the check for invalid characters on content-length header values
doesn't reject empty headers, which can pass through. And since they
don't have a value, they're not merged with next ones, so it is
possible to pass a request that has both an empty content-length and
a populated one. Such requests are invalid and the vast majority of
servers will reject them. But there are certainly still a few
non-compliant servers that will only look at one of them,
considering the empty value equals zero and be fooled with this.
Thus the problem is not as much for mainstream users as for those
who develop their own HTTP stack or who …

OCPBUGS-17653: haproxy/template: mitigate CVE-2023-40225

---

pkg/router/template/router.go
pkg/router/template/router_test.go

Fix regression introduced with [NE-822](https://issues.redhat.com//browse/NE-822) for services with a single endpoint having weight=0 that are wrongly sent traffic to.
Modified for backport to 4.12 to remove dependencies on https://github.com/openshift/router/pull/439.
`pkg/router/template/router.go`: Fix logic for single endpoint services to use weight=0. Change `units` variable to `weight` `pkg/router/template/router_test.go`: Add unit tests for weight=0
Modified-by: Grant Spence <gspence@redhat.com>

OCPBUGS-18639: properly handle weight=0

---

pkg/router/controller/unique_host.go

When a route is rejected due to the host already being claimed, it was
always selecting the first route but the first route is not guaranteed
to being the conflicting route.
All routes for the host are retrieved using the 'RoutesForHost'
function and that function returns a slice of routes derived from a
map in the 'hostIndex' structure. Since maps do not guarantee order,
the first route was not necessarily the oldest.
The fix is to first sort the conflicting routes based on their
submission time, and then pick the newest.
Fixes: https://issues.redhat.com/browse/OCPBUGS-16707

OCPBUGS-16707: UniqueHost: Fix incorrect identification of conflicting route

---

images/router/haproxy/conf/haproxy-config.template

In HAProxy 2.6, the 'strict limits' setting, which enforces resource
limits (e.g., the number of open files), became the default behaviour.
Consequently, any failure to configure resource limits now results in
fatal errors. This change introduces 'no strict-limits' in the
template to revert to the behaviour of HAProxy 2.2. This is necessary
to ensure the router starts successfully when a maxconn setting cannot
be satisfied.
The HAProxy documentation for 'strict-limits' states:
Makes process fail at startup when a setrlimit fails. HAProxy
tries to set the best setrlimit according to what has been
calculated. If it fails, it will emit a warning. This option is
here to guarantee an explicit failure of HAProxy when those limits
fail. It is enabled by default. It may still be forcibly disabled …

OCPBUGS-21803: haproxy-template: Add 'no strict-limits' to address HAProxy 2.6 issue

---

.ci-operator.yaml
images/router/base/Dockerfile.rhel

Update the base image for the router from RHEL8 to RHEL9.
`.ci-operator.yaml`: Update ci-operator build_root imagestream
`images/router/base/Dockerfile.rhel`: Update builder and router image
Perf & Scale run documented in [NE-1448](https://issues.redhat.com//browse/NE-1448)

NE-1446: Update to RHEL9 base image

---

hack/Dockerfile.debug
hack/Makefile.debug

The PR aims at fixing the broken RPM link in `hack/Dockerfile.debug` as well as bring a better building experience by:
- migrating the base image to the universal one
- using `podman` as the image builder

NO-JIRA: hack - fix broken RPM link and use UBI image in Dockerfile.debug, use podman in Makefile.debug

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

Add logic to the extended route validation to reject any MD5-based certs.
`pkg/router/routeapihelpers/validation.go`: Add logic to validateCertificatePEM to reject certs with MD5
`pkg/router/routeapihelpers/validation_test.go`: Add unit test case for validating route with cert using MD5

OCPBUGS-26539: Reject routes with MD5 certs

---

hack/Dockerfile.debug
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8
images/router/haproxy/conf/haproxy-config.template

**Context:**
This pull request bumps HAProxy to the haproxy28 RPM. It also addresses the changes introduced in HAProxy 2.8, specifically the default enabling of ALPN h2. It presents an update to our HAProxy configuration, affecting the `fe_sni` and `fe_no_sni` TLS listeners.
**Changes:**
- The introduction of an unconditional `no-alpn` directive in the HAProxy template for `fe_sni` and `fe_no_sni` listeners.
- This change is independent of the HTTP/2 status in the ingress controller and aims to maintain consistent behavior with previous OpenShift / HAProxy releases.
- Updates the RPM package from haproxy26 to haproxy28.
**Rationale:**
In the HAProxy 2.8 [release notes](https://www.mail-archive.com/haproxy@formilux.org/msg43600.html), it is highlighted that HTTP/2 is now automatically …

NE-1444: Upgrade OpenShift Router to HAProxy 2.8

---

hack/Dockerfile.debug
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8
images/router/haproxy/conf/haproxy-config.template

Reverts #551 ; tracked by [TRT-1507](https://issues.redhat.com//browse/TRT-1507)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Testing a revert here, we are seeing a crash in metal-ipi jobs on missing socat binary in an haproxy container.
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-sdn-bm
```
CC: @frobware
<div align="right">
PR …

TRT-1507: Revert #551 "NE-1444: Upgrade OpenShift Router to HAProxy 2.8"

---

hack/Dockerfile.debug
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/Dockerfile.rhel8
images/router/haproxy/conf/haproxy-config.template

This PR addresses the absence of the `socat` package in container builds, which has been reported as missing in metal-ipi jobs. It explicitly adds the `socat` package to the container builds to rectify this issue. The need for a direct inclusion of `socat` suggests a potential change in the baseline environment provided by RHEL 9, given that in previous RHEL 8 builds, `socat` was not explicitly included but was nonetheless present and extensively used for debugging HAProxy issues through its stats socket.
This PR reverts [openshift/router#561](https://github.com/openshift/router/pull/561).
cc @dgoodwin

NE-1444: Bump HaProxy to the latest version 2.8

---

pkg/router/metrics/probehttp/probehttp.go

This commit modifies the logging within DoHTTPProbe() to directly log
specific fields of the HTTP response (StatusCode and Status) instead
of attempting to log the entire response object.
This modification resolves issues related to logging non-serialisable
objects by directly logging specific, serialisable fields of the HTTP
response. This approach enhances log clarity and utility for
debugging, eliminating errors caused by attempting to serialise
non-serialisable types.
Prior to this change we would log (and reformatted for clarity):
```console
I0306 12:08:49.475681       1 probehttp.go:108]
"msg"="probe succeeded"
"response"=<<error: json: unsupported type: func() (io.ReadCloser, error)>>
"url"="http://localhost:80/_______internal_router_healthz".
```
With this change we now log: …

OCPBUGS-30314: Refactor logging in DoHTTPProbe to avoid serialisation errors

---

hack/Dockerfile.debug

In line with OCP-4.16's upgrade to RHEL 9, this PR updates
`hack/Dockerfile.debug` to use a RHEL 9 base image (`ubi9`) instead of
the previous RHEL 8 base (`ubi8`). This ensures our debug environment
mirrors the production environment's underlying OS.
Related change: https://github.com/openshift/router/pull/544

NO-JIRA: hack/Dockerfile.debug: use ubi9 for base image

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper.go
pkg/router/template/util/rewritetarget/rewritetarget.go
pkg/router/template/util/rewritetarget/rewritetarget_test.go

Process the `haproxy.router.openshift.io/rewrite-target` annotation value to prevent HaProxy configuration issues while maintaining API compatibility. Properly handle values with spaces, backslashes, and other special characters.
Add a new package, rewritetarget, to organize the functions that process the rewrite target annotation. Add a separate unit test package, rewritetarget_test, to enforce black-box testing principles.
- `images/router/haproxy/conf/haproxy-config.template`: Call processRewriteTarget function in template.
- `pkg/router/template/rewritetarget/rewritetarget.go`: New package with functions to process the rewrite target annotation.
- `pkg/router/template/rewritetarget/rewritetarget_test.go`: Unit test SanitizeInput function.
- `pkg/router/template/template_helper.go`: …

OCPBUGS-22739: Properly handle rewrite-target annotation

---

images/router/haproxy/conf/haproxy-config.template

This PR addresses a known issue ([OCPBUGS-32044](https://issues.redhat.com//browse/OCPBUGS-32044)) encountered with certain HTTP clients, notably the Apache HTTP client (prior to version 5), where closed idle connections are erroneously reused. To mitigate this, we introduce the `idle-close-on-response` option, which is now applied to all frontends operating in HTTP mode. Note that the `public_ssl` frontend remains in TCP mode and is unaffected by this change.
Spin off of https://github.com/openshift/router/pull/572.

OCPBUGS-32044: Introduce 'idle-close-on-response' option for frontends

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go
pkg/router/template/plugin_test.go

Add logic to the extended route validation to reject any SHA1-based certs as they are no longer supported in 4.16+.
Also, the router will now clear `UnservableInFutureVersions` conditions for routes with SHA1 certs. This is desirable because the router is now rejecting routes with SHA1 cert and `UnservableInFutureVersions` no longer applies.
Previously, #555 was merged into 4.16 which sets `UnservableInFutureVersions` conditions for routes with SHA1 certs. #555  PR was intended to merge in 4.16 and backport into 4.15. This PR (#552) needs to partially reverts changes in #555 because this PR (#552) now rejects SHA1 certificates. This PR (#552) is ONLY intended for 4.16+ (it's not going to be backported).

OCPBUGS-26498: Reject routes with SHA1 certs

---

pkg/cmd/infra/router/router.go
pkg/cmd/infra/router/template.go
pkg/router/controller/upgrade_validation.go
pkg/router/template/plugin_test.go

Add `--debug-upgrade-validation-force-add-condition` and `--debug-upgrade-validation-force-remove-condition` as arguments to the
openshift-router. These force add or force remove the `UnservableInFutureVersions` condition to allow for an E2E test to do contention testing on a condition-level.
Origin Test PR that these arguments support: https://github.com/openshift/origin/pull/28710

"OCPBUGS-26498: Add Upgrade Validation force arguments for running E2E tests"

---

pkg/router/template/router.go
pkg/router/template/router_test.go

The previous logic, which reduced the weight to 1 when there was only one service, didn't filter out inactive services. If there's only one active service, there's no need for a weight greater than 1 because traffic is directed only to active services.
Additionally, the template logic correctly accounted for active services when setting the algorithm, resulting in "random" being set in situations where our logic didn't reduce the active service's weight to 1.
While this isn't inherently problematic, using the "random" algorithm with higher weights significantly increases memory usage on HaProxy startup. This can lead to excessive memory usage in scenarios where a user has many inactive services or routes backends using weight 0.

OCPBUGS-29690: Count active services before setting weight to 1

---

pkg/router/controller/contention.go
pkg/router/controller/extended_validator.go
pkg/router/controller/host_admitter.go
pkg/router/controller/status.go
pkg/router/controller/status_test.go
pkg/router/controller/unique_host.go
pkg/router/controller/upgrade_validation.go
pkg/router/template/configmanager/haproxy/blueprint_plugin.go
pkg/router/template/plugin.go
pkg/router/writerlease/writerlease.go

We found that the router's contention tracker was slower after updates were made to support the UnservableInFutureVersions condition. This lag sometimes causes routers to update the route status before the contention tracker detected an update, leading to the per-route contention logic not activating.
In such scenarios, the maxContentions logic eventually activates, temporarily preventing the router from making any updates to the routes. This commit improves the efficiency of the ingressConditionsEqual function to help mitigate this type of issues.
Related [slack thread](https://redhat-internal.slack.com/archives/CBWMXQJKD/p1714425622177519).
```
$ go test -bench=. -run=Benchmark_ingressConditionsEqual ./... -benchtime=10s -benchmem
[...] 
goos: linux
goarch: amd64
pkg: …
```

OCPBUGS-26498: Make ingressConditionsEqual more efficient

---

pkg/router/controller/status.go
pkg/router/controller/status_test.go

Both performIngressConditionUpdate and performIngressConditionRemoval functions add tasks to the writerlease queue even if no work needed to be done. This commit optimizes the Upgrade Validation plugin by ensuring that tasks for updating UnservableInFutureVersions are only added to the queue when changes are required.
This reduction in unnecessary work significantly lowers the frequency of lease extensions. Previously, excessive lease extensions could delay route status updates under certain conditions, such as during temporary contention periods
where a router pod gets demoted to a follower. After the contention is resolved, the pod’s subsequent retry will be delayed more than necessary.
Additionally, this update provides a clearer indication of when updates are actually required, but …

OCPBUGS-26498: Optimize Upgrade Validation plugin by skipping unnecessary changes

---

pkg/router/router_test.go
pkg/router/template/router.go
pkg/router/template/template_helper.go

Add a check in `generateHAProxyCertConfigMap` for whether the same certificate is specified on more than one route, or whether a route specifies the default certificate as a custom certificate.  If either of these conditions is detected, then configure HAProxy not to allow HTTP/2 client connections to this route.
Using the same certificate for multiple routes signals to Web browsers that they can do HTTP/2 connection coalescing.  This means that a browser could open a connection for one route and then re-use this connection to connect to a second route, which can cause the client's request to go to the wrong backend server.  We try to prevent this client behavior by advertising HTTP/2 in TLS ALPN only for routes that have unique certificates.
In general, we assume that if a route …

OCPBUGS-29373: generateHAProxyCertConfigMap: No H2 with dup certs

---

pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go
pkg/router/template/util/haproxytime/duration_parser.go
pkg/router/template/util/haproxytime/duration_parser_test.go
pkg/router/template/util/util.go

* OCPBUGS-6958: Fix clipHAProxyTimeoutValue so that:
* a value larger than time.ParseDuration can handle is clipped to the HAProxy max timeout
* a value that cannot be properly parsed for other reasons is set to empty instead of being silently allowed
To check that time.ParseDuration is experiencing overflow, add a new ParseHAProxyDuration to the util package so we can evaluate the errors returned by time.ParseDuration without sacrificing its authority in parsing time strings.
* add haproxytime
* use pkg/router/template/util/haproxytime
* drop existing ParseHAProxyDuration
* OCPBUGS-6958: Fix clipHAProxyTimeoutValue so that:
* a value larger than time.ParseDuration can handle is clipped to the HAProxy max timeout
* a value that cannot be properly parsed for other reasons is set to empty …

OCPBUGS-30773: OCPBUGS 6958 backport to 4.14

---

pkg/router/template/router.go
pkg/router/template/router_test.go

**This is a manual cherry-pick of https://github.com/openshift/router/pull/576**
**Merge Conflict Resolution:**
- A merge conflict occurred because https://github.com/openshift/router/pull/439 is not backported to 4.12
- We added the port parameter in  `numberOfEndpoints(key, port)` so it counts endpoints only for the port that the router is using.
- Without backporting https://github.com/openshift/router/pull/439, it will double count the endpoints if you have 2 ports.
- Our backport logic, we now additionally leverage `r.numberOfEndpoints(key)` to see if it's an active endpoint, i.e. if endpoints are > 0. `port` only matters if there are > 0 endpoints. Filtering by `port` might cause > 0 endpoint situations to change, but when there are 0 endpoints, number of ports has no impact.
- …

[release-4.12] OCPBUGS-33517: Count active services before setting weight to 1

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/template/template_helper.go
pkg/router/template/util/rewritetarget/rewritetarget.go
pkg/router/template/util/rewritetarget/rewritetarget_test.go

This is an manual cherry-pick of https://github.com/openshift/router/pull/534
Process the `haproxy.router.openshift.io/rewrite-target` annotation value to prevent HaProxy configuration issues while maintaining API compatibility. Properly handle values with spaces, backslashes, and other special characters.
Add a new package, rewritetarget, to organize the functions that process the rewrite target annotation. Add a separate unit test package, rewritetarget_test, to enforce black-box testing principles.

[release-4.14] OCPBUGS-32634: Properly handle rewrite-target annotation

---

.gitleaks.toml
go.mod
go.sum
pkg/cmd/infra/router/router.go
pkg/cmd/infra/router/template.go
pkg/router/controller/contention.go
pkg/router/controller/extended_validator.go
pkg/router/controller/host_admitter.go
pkg/router/controller/host_admitter_test.go
pkg/router/controller/status.go
pkg/router/controller/status_test.go
pkg/router/controller/unique_host.go
pkg/router/controller/upgrade_validation.go
pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go
pkg/router/template/configmanager/haproxy/blueprint_plugin.go
pkg/router/template/plugin.go
pkg/router/template/plugin_test.go
pkg/router/writerlease/writerlease.go
vendor/github.com/openshift/api/route/v1/generated.proto
vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/route/v1/route.crd.yaml
vendor/github.com/openshift/api/route/v1/types.go
vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

Manual cherry-pick of https://github.com/openshift/router/pull/555, https://github.com/openshift/router/pull/575, https://github.com/openshift/router/pull/588, https://github.com/openshift/router/pull/587 (in that order). All required to support new Upgrade Validation plugin.
This PR adds support for setting a new status condition type, UnservableInFutureVersions, when a SHA1 cert is detected on a route. It accomplishes this by adding a new plugin, the upgrade validation plugin. This plugin is simple: when a route configuration that is unsupported in the future is detected, it adds a UnservableInFutureVersions status condition to the route. When the problematic configuration is no longer detected, it clears/removes the UnservableInFutureVersions condition.
In order to support updating a …

[release-4.15] OCPBUGS-28928: Upgrade Validation plugin for SHA1 certs

---

hack/Dockerfile.debug
images/router/haproxy/Dockerfile
images/router/haproxy/Dockerfile.ocp
images/router/haproxy/Dockerfile.rhel
images/router/haproxy/conf/haproxy-config.template
pkg/cmd/infra/router/router.go
pkg/router/router_test.go
pkg/router/template/configmanager/haproxy/manager.go
pkg/router/template/router.go
pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go
pkg/router/template/util/haproxy/allowlist.go
pkg/router/template/util/haproxy/allowlist_test.go

Use the new annotation key "haproxy.router.openshift.io/ip_allowlist" in addition to the old "haproxy.router.openshift.io/ip_whitelist" annotation key. Continue to allow the old annotation key for now, but use the new one if it is present.
If a route has annotations with both keys, the annotation with the new key is used, and the annotation with the old key is ignored.
Also rename some template helper functions.  **Note that this is technically a breaking change for custom config templates!**
Also rename internal consts, variables, functions, struct fields, and HAProxy ACLs to change "whitelist" to "allowlist" and "blacklist" to "denylist".
* `images/router/haproxy/conf/haproxy-config.template`: Check for both the old annotation and new annotation keys.  Rename the associated acl and file …

NE-1811: Rename the allowlist route annotation

---

images/router/haproxy/conf/haproxy-config.template

This PR ensures that ALPN protocol negotiation is enabled for reencrypt routes when the Dynamic Configuration Manager (DCM) is active, aligning the behavior with [non-DCM configurations](https://github.com/openshift/router/blob/d095bdbb4777677f5317e49fb353f41b9c1a22e7/images/router/haproxy/conf/haproxy-config.template#L728-L729).
The gap to support HTTP2 workloads for reencrypt routes was found during [the smoke testing](https://github.com/openshift/cluster-ingress-operator/pull/1113#issuecomment-2315530761).

NE-1815: Enable ALPN for reencrypt routes when DCM is enabled

---

images/router/haproxy/conf/haproxy-config.template

- Introduced a "dynamic" option for ["cookie" directive](https://docs.haproxy.org/2.8/configuration.html#4-cookie) used on plain HTTP, edge and re-encrypt routes. This option activates the dynamic cookie creation per server, applicable only for dynamic server slots (static server slots set cookie values explicitly). Without this option, dynamic servers will not set a cookie value.
- Added the ["dynamic-cookie-key" directive](https://docs.haproxy.org/2.8/configuration.html#dynamic-cookie-key) to re-ecrypt routes to align the dynamic cookie handling across all route types (plain HTTP and edge already have "dynamic-cookie-key").This directive is used to generate a unique cookie value for a each route.
`Set-Cookie` header sent from dynamic servers before this change:
```
set-cookie: …
```

NE-1815: Activate dynamic cookies for dynamic server slots (DCM)

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go
pkg/router/template/configmanager/haproxy/backend.go
pkg/router/template/configmanager/haproxy/manager.go

Rename the `mustCreate` type used in tests to `mustCreateRoute`.
Define a new `mustCreateEndpointSlice` type for tests, and use it to define new test cases where the endpointslice associated with the route specifies `appProtocol` with the recognized value "h2c" and unrecognized values "unknown-value" and "kubernetes.io/h2c".
Recognize both "h2c" and "kubernetes.io/h2c" as valid values for `appProtocol`.  Update the expectations for the "route with appProtocol: kubernetes.io/h2c" test case accordingly. 
--- 
Follow-up to  #328.

OCPBUGS-42972: Support appProtocol: kubernetes.io/h2c

---

images/router/haproxy/conf/haproxy-config.template
pkg/router/router_test.go
pkg/router/template/plugin_test.go
pkg/router/template/router.go
pkg/router/template/types.go

This PR introduces  [the "verifyhost" configuration setting](https://docs.haproxy.org/2.8/configuration.html#verifyhost) to dynamic server slots during template rendering. This ensures consistent behavior with static servers.
The "verifyhost" uses the FQDN of the primary service only, as it's not feasible to predict which service endpoint will be used when alternate backends are available.Consequently, dynamic servers for re-encrypt routes are not intended to handle alternate backend endpoints. A reload is forced when endpoint changes occur for alternate backend services in a re-encrypt route.
The commit which added the server certificate verification without `verifyhost`: https://github.com/openshift/router/commit/50a330de5a3da9636b36b5e9e62ddbc374b99524.

NE-1815: Add verifyhost to dynamic server slots for re-encrypt routes (DCM)

---

images/router/haproxy/conf/haproxy-config.template

Replace the hard-coded `idle-close-on-response` setting with a conditional based on the IngressController's `spec.idleConnectionTerminationPolicy` field, which controls whether HAProxy maintains idle frontend connections during reloads or closes them immediately.
The default behaviour for OCP 4.19 returns to closing idle connections immediately, reversing https://issues.redhat.com/browse/OCPBUGS-32044 which had made 'option idle-close-on-response' always present in the HAProxy configuration.
References:
- The field `idleConnectionTerminationPolicy` was added in https://github.com/openshift/api/pull/2102
- cluster-ingress-operator e2e test in openshift/cluster-ingress-operator#1166

OCPBUGS-43745: Add support for IdleCloseTerminationPolicy

---

pkg/router/routeapihelpers/validation.go
pkg/router/routeapihelpers/validation_test.go

Previously, only SHA1 leaf certs were rejected. However, in 4.16, any SHA1 cert that is CA-signed (not self-signed) is unsupported. This led to cases were routes with SHA1 intermediate CA certs were accepted, but HAProxy rejects them. Self-signed SHA1 certificates (i.e. root CA) remain supported since they are not subject to verification.
This update ensures all route certs, including the server, CA, and destination CA certs, are inspected, and any SHA1 cert that is not self-signed is rejected.
Additionally, explicitly reject DSA SHA1 certificates. While all DSA certificates are already rejected by the router, this change provides a clearer and more precise rejection error message.

OCPBUGS-45290: Reject All CA-Signed Certs Using SHA1

---

pkg/router/template/template_helper.go
pkg/router/template/template_helper_test.go

This PR updates the `parseIPList` function to handle IP lists containing invalid IPs or CIDRs more gracefully. Previously, the function would return an empty string as soon as it encountered an invalid IP or CIDR. This update ensures that the function will now continue processing the rest of the list and return a space-separated string of all valid IPs and CIDRs.
- Modified `parseIPList` to:
- Log all invalid entries for troubleshooting.
- Return a string of valid IPs and CIDRs, or an empty string if none are valid.
- **Improved Robustness**: The function now handles mixed validity IP lists more gracefully, allowing valid entries to be processed even if there are some invalid entries.
- **Enhanced Debugging**: Logging of invalid IPs or CIDRs provides better visibility into issues with …

OCPBUGS-39403: Fix parseIPList to Continue Processing After Invalid IPs and Return Valid IPs

---

images/router/haproxy/conf/haproxy-config.template

When servers are listed using FQDN names rather than IP addresses, HAProxy will attempt to resolve these names at startup. In the event that a name cannot be resolve, HAProxy will fail. To overcome this, use the 'init-addr' such that even if name resolution fails, HAProxy will still start normally. Any server that fails name resolution will be set in the DOWN state. Note that the key here is the 'none' keyword used with 'init-addr'
Also note that this option is being set via the 'default-server' option in the 'defaults' section and therefore applied to all servers listed in the configuration.

OCPBUGS-55506: Prevent startup failures due to name resolution

---

images/router/haproxy/conf/haproxy-config.template

As per the bug, there is some extra white space in the template and it shows up before the "frontend public" item as noted

OCPBUGS-60257: fix extra space in haproxy template
